name: 'bike_share'
version: '1.0.0'
config-version: 2

profile: 'bike_share'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bike_share:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
