version: 2

sources:
  - name: raw
    description: "Raw bike share data from source CSV files"
    schema: main
    tables:
      - name: raw_rides
        description: "Raw rides data from bike share system"
        columns:
          - name: trip_duration
            description: "Duration of the trip in seconds"
          - name: start_time
            description: "Start time of the trip"
          - name: stop_time
            description: "End time of the trip"
          - name: start_station_id
            description: "ID of the starting station"
          - name: start_station_name
            description: "Name of the starting station"
          - name: start_station_latitude
            description: "Latitude of the starting station"
          - name: start_station_longitude
            description: "Longitude of the starting station"
          - name: end_station_id
            description: "ID of the ending station"
          - name: end_station_name
            description: "Name of the ending station"
          - name: end_station_latitude
            description: "Latitude of the ending station"
          - name: end_station_longitude
            description: "Longitude of the ending station"
          - name: bike_id
            description: "Unique identifier for the bike used"
          - name: user_type
            description: "Type of user (Member/Casual)"
          - name: birth_year
            description: "Birth year of the user"
          - name: gender
            description: "Gender of the user (0: Unknown, 1: Male, 2: Female)"
          - name: trip_duration_in_min
            description: "Duration of the trip in minutes"

