version: 2

models:
  - name: int_time
    description: "Temporal dimension with calendar hierarchies"
    columns:
      - name: date
        description: "Calendar date from ride data"
        tests:
          - not_null
      
      - name: year
        description: "Year extracted from date"
        tests:
          - not_null
      
      - name: month
        description: "Month number (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      
      - name: day
        description: "Day of month"
        tests:
          - not_null
      
      - name: day_of_week
        description: "Day of week (0-6, where 0 is Sunday)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
      
      - name: hour
        description: "Hour of day (0-23)"
        tests:
          - not_null
      
      - name: is_weekend
        description: "Flag indicating if date is a weekend"
        tests:
          - not_null
      
      - name: time_of_day
        description: "Part of day (Morning, Afternoon, Evening, Night)"
        tests:
          - not_null
          - accepted_values:
              values: ['Morning', 'Afternoon', 'Evening', 'Night']

  - name: int_stations
    description: "Enriched station data with traffic metrics"
    columns:
      - name: station_id
        description: "Unique identifier for the station"
        tests:
          - not_null
          - unique
      
      - name: station_name
        description: "Name of the station"
        tests:
          - not_null
      
      - name: latitude
        description: "Latitude coordinate of the station"
        tests:
          - not_null
      
      - name: longitude
        description: "Longitude coordinate of the station"
        tests:
          - not_null
      
      - name: start_count
        description: "Number of rides starting from this station"
        tests:
          - not_null
      
      - name: end_count
        description: "Number of rides ending at this station"
        tests:
          - not_null
      
      - name: total_traffic
        description: "Total number of arrivals and departures"
        tests:
          - not_null

      - name: net_flow
        description: "Difference between departures and arrivals (positive means more departures)"

  - name: int_rides_enriched
    description: "Enriched ride data with station and time information"
    columns:
      - name: trip_duration
        description: "Duration of the trip in seconds"
        tests:
          - not_null
      
      - name: start_time
        description: "Start time of the trip"
        tests:
          - not_null
      
      - name: stop_time
        description: "End time of the trip"
        tests:
          - not_null
      
      - name: start_station_id
        description: "ID of the starting station"
        tests:
          - not_null
      
      - name: end_station_id
        description: "ID of the ending station"
        tests:
          - not_null
      
      - name: bike_id
        description: "Unique identifier for the bike used"
        tests:
          - not_null
      
      - name: user_type
        description: "Type of user (Member/Casual)"
        tests:
          - not_null
      
      - name: trip_duration_in_min
        description: "Duration of the trip in minutes"
        tests:
          - not_null
      
      - name: route_id
        description: "Concatenated start and end station IDs"
        tests:
          - not_null

